# Generated by Django 3.1.7 on 2021-03-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(related_name='author_faves', to='homepage.Recipe'),
        ),
    ]
